// Generated by scripts/import-exercises-dataset.mjs. Do not edit by hand.
export const EXERCISE_CATALOG_COUNT = 2836;
export const EXERCISE_CATALOG_SOURCE_COUNTS = { exercisesDataset: 1324, freeExerciseDb: 741, wger: 771 } as const;
