const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));

export function shareCardCopy({type,score,change,language="en"}){
  const zh=language==="zh";const title=type==="form"?(zh?"我的深蹲动作评分":"MY SQUAT SCORE"):(zh?"我的体态趋势评分":"MY POSTURE TREND");
  const progress=typeof change==="number"?(change===0?(zh?"与上次持平":"SAME AS LAST SCAN"):(change>0?`↑ +${change}`:`↓ ${change}`)+(zh?" 较上次":" SINCE LAST SCAN")):(zh?"个人基准已建立":"PERSONAL BASELINE SET");
  return {title,progress,shareText:zh?`我的练一下 · ONE SET ${type==="form"?"深蹲动作":"体态趋势"}评分是 ${score}/100。评分只基于可观察表现。`:`My ONE SET ${type==="form"?"squat form":"posture trend"} score is ${score}/100, based only on observable performance.`};
}

export async function generateShareCard({type,score,confidence,metrics,change=null,language="en"}){
  const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");
  const copy=shareCardCopy({type,score,change,language});const lime="#667663",cream="#f3eee4",muted="#737a73",panel="#fffaf2",coral="#c1847a",ink="#2d342f";
  const gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,"#f3eee4");gradient.addColorStop(.55,"#f8f3ea");gradient.addColorStop(1,"#ecefe8");ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);
  const glow=ctx.createRadialGradient(870,140,0,870,140,520);glow.addColorStop(0,"rgba(193,132,122,.22)");glow.addColorStop(1,"rgba(193,132,122,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,1080,700);
  ctx.fillStyle=lime;ctx.fillRect(72,70,16,16);ctx.font="900 36px Arial, Microsoft YaHei, sans-serif";ctx.fillText("练一下 · ONE SET",104,88);ctx.fillStyle=muted;ctx.font="700 18px Arial, Microsoft YaHei, sans-serif";ctx.letterSpacing="3px";ctx.fillText("FILM. FIX. PROGRESS.",72,132);
  roundedRect(ctx,72,184,936,330,34,panel);ctx.fillStyle=lime;ctx.font="800 23px Arial, Microsoft YaHei, sans-serif";ctx.fillText(copy.title,112,238);ctx.fillStyle=ink;ctx.font="900 168px Arial, Microsoft YaHei, sans-serif";ctx.fillText(String(score),104,422);ctx.fillStyle=muted;ctx.font="700 34px Arial, Microsoft YaHei, sans-serif";ctx.fillText("/100",390,418);
  ctx.strokeStyle="#d9ddd4";ctx.lineWidth=22;ctx.beginPath();ctx.arc(824,346,104,-Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.strokeStyle=score>=82?lime:score>=65?"#b18a55":coral;ctx.beginPath();ctx.arc(824,346,104,-Math.PI/2,-Math.PI/2+Math.PI*2*clamp(score,0,100)/100);ctx.stroke();ctx.fillStyle=ink;ctx.font="900 42px Arial, sans-serif";ctx.textAlign="center";ctx.fillText(String(score),824,360);ctx.textAlign="left";
  const rows=(Array.isArray(metrics)?metrics:[]).filter(metric=>metric&&metric.assessed!==false).slice(0,5);let y=570;for(const metric of rows){ctx.fillStyle=ink;ctx.font="700 25px Arial, Microsoft YaHei, sans-serif";ctx.fillText(metric.label||metric.key,82,y+24);ctx.fillStyle="#d9ddd4";roundedRect(ctx,400,y,450,24,12,"#d9ddd4");const value=clamp(Number(metric.score)||0,0,100);roundedRect(ctx,400,y,450*value/100,24,12,value>=82?lime:value>=68?"#b18a55":coral);ctx.fillStyle=ink;ctx.font="900 28px Arial, sans-serif";ctx.textAlign="right";ctx.fillText(String(Math.round(value)),982,y+24);ctx.textAlign="left";y+=92;}
  roundedRect(ctx,72,1050,936,120,26,"#ecefe8");ctx.fillStyle=lime;ctx.font="900 31px Arial, Microsoft YaHei, sans-serif";ctx.fillText(copy.progress,112,1118);ctx.fillStyle=muted;ctx.font="700 20px Arial, Microsoft YaHei, sans-serif";ctx.fillText(`${confidence}% ${language==="zh"?"结果可信度":"RESULT CONFIDENCE"}`,112,1155);
  ctx.fillStyle=ink;ctx.font="800 24px Arial, Microsoft YaHei, sans-serif";ctx.fillText(language==="zh"?"只评价动作与体态趋势，不评价外貌":"MOVEMENT & POSTURE TRENDS — NEVER APPEARANCE",72,1252);ctx.fillStyle=muted;ctx.font="600 17px Arial, Microsoft YaHei, sans-serif";ctx.fillText(language==="zh"?"非医疗或伤病诊断":"NOT MEDICAL OR INJURY DIAGNOSIS",72,1290);
  const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Card export failed")),"image/png",.96));return new File([blob],`one-set-${type}-score-${score}.png`,{type:"image/png"});
}

export async function shareOrDownloadCard(input){
  const file=await generateShareCard(input);const copy=shareCardCopy(input);
  if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:`练一下 · ONE SET · ${copy.title}`,text:copy.shareText,files:[file]});return"shared"}
  const url=URL.createObjectURL(file);const anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);return"downloaded";
}

export async function shareWorkoutSummary({focus,duration,exercises,sets,totalVolume,rating,language="en"}){
  const zh=language==="zh";const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");
  const lime="#667663",cream="#f3eee4",muted="#737a73",panel="#fffaf2",coral="#c1847a",ink="#2d342f";const focusLabel={full:zh?"全身":"FULL BODY",upper:zh?"上肢":"UPPER BODY",lower:zh?"下肢":"LOWER BODY",pushpull:zh?"胸与背":"PUSH + PULL",core:zh?"核心":"CORE"}[focus]||String(focus).toUpperCase();const ratingLabel={easy:zh?"轻松完成":"EASY",right:zh?"恰到好处":"RIGHT",hard:zh?"挑战完成":"HARD",pain:zh?"记录了不适":"PAIN FLAG"}[rating]||"COMPLETE";
  const gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,"#f3eee4");gradient.addColorStop(1,"#e7ece4");ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);const glow=ctx.createRadialGradient(850,210,0,850,210,520);glow.addColorStop(0,"rgba(102,118,99,.2)");glow.addColorStop(1,"rgba(102,118,99,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,1080,800);
  ctx.fillStyle=lime;ctx.fillRect(72,70,16,16);ctx.font="900 36px Arial, Microsoft YaHei, sans-serif";ctx.fillText("练一下 · ONE SET",104,88);ctx.fillStyle=muted;ctx.font="700 18px Arial, Microsoft YaHei, sans-serif";ctx.fillText("PLAN. TRAIN. PROGRESS.",72,132);
  roundedRect(ctx,72,188,936,388,34,panel);ctx.fillStyle=lime;ctx.font="800 24px Arial, Microsoft YaHei, sans-serif";ctx.fillText(zh?"今天训练完成":"TODAY'S WORKOUT COMPLETE",112,242);ctx.fillStyle=ink;ctx.font="900 76px Arial, Microsoft YaHei, sans-serif";ctx.fillText(focusLabel,108,348);ctx.fillStyle=muted;ctx.font="700 25px Arial, Microsoft YaHei, sans-serif";ctx.fillText(`${duration} MIN  ·  ${exercises} ${zh?"个动作":"MOVES"}  ·  ${sets} ${zh?"组":"SETS"}`,112,404);ctx.fillStyle=coral;ctx.font="900 29px Arial, Microsoft YaHei, sans-serif";ctx.fillText(ratingLabel,112,497);
  const metrics=[[zh?"训练容量":"VOLUME",totalVolume>=1000?`${(totalVolume/1000).toFixed(1)} t`:`${Math.round(totalVolume)} kg`],[zh?"完成组数":"SETS",String(sets)],[zh?"训练时长":"TIME",`${duration} min`]];metrics.forEach(([label,value],index)=>{const x=72+index*316;roundedRect(ctx,x,630,292,178,24,"#fffaf2");ctx.fillStyle=muted;ctx.font="800 18px Arial, Microsoft YaHei, sans-serif";ctx.fillText(label,x+28,682);ctx.fillStyle=ink;ctx.font="900 42px Arial, Microsoft YaHei, sans-serif";ctx.fillText(value,x+28,752)});
  roundedRect(ctx,72,880,936,180,28,"#dfe7dc");ctx.fillStyle=lime;ctx.font="900 25px Arial, Microsoft YaHei, sans-serif";ctx.fillText(zh?"PLAN → TRAIN → LOG → PROGRESS":"PLAN → TRAIN → LOG → PROGRESS",112,946);ctx.fillStyle=ink;ctx.font="800 32px Arial, Microsoft YaHei, sans-serif";ctx.fillText(zh?"下一场训练已经在路上。":"Your next session starts from this record.",112,1004);
  ctx.fillStyle=ink;ctx.font="800 24px Arial, Microsoft YaHei, sans-serif";ctx.fillText("练一下 · ONE SET",72,1245);ctx.fillStyle=muted;ctx.font="600 17px Arial, Microsoft YaHei, sans-serif";ctx.fillText(zh?"训练记录，不评判外貌。":"TRAINING RECORDS · NEVER APPEARANCE",72,1285);
  const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Card export failed")),"image/png",.96));const file=new File([blob],"one-set-workout-complete.png",{type:"image/png"});const shareText=zh?`我刚完成了一场 ${focusLabel} 训练：${duration} 分钟 · ${sets} 组。`:`I just completed a ${focusLabel.toLowerCase()} workout: ${duration} min · ${sets} sets.`;
  if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"练一下 · ONE SET · Workout complete",text:shareText,files:[file]});return"shared"}const url=URL.createObjectURL(file);const anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);return"downloaded";
}

function roundedRect(ctx,x,y,width,height,radius,color){ctx.beginPath();ctx.roundRect(x,y,width,height,radius);ctx.fillStyle=color;ctx.fill()}
